## File Name: RcppExports.R
## File Version: 0.004035
# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mnlfa_rcpp_plogis <- function(x) {
    .Call('_mnlfa_mnlfa_rcpp_plogis', PACKAGE='mnlfa', x)
}

mnlfa_rcpp_calc_probs_2pl <- function(a, b, theta, y, y_resp) {
    .Call('_mnlfa_mnlfa_rcpp_calc_probs_2pl', PACKAGE='mnlfa', a, b, theta, y, y_resp)
}

mnlfa_rcpp_calc_dnorm <- function(a, b, psi, theta, y, y_resp) {
    .Call('_mnlfa_mnlfa_rcpp_calc_dnorm', PACKAGE='mnlfa', a, b, psi, theta, y, y_resp)
}

mnlfa_rcpp_calc_probs_gpcm <- function(a, b, theta, y, y_resp) {
    .Call('_mnlfa_mnlfa_rcpp_calc_probs_gpcm', PACKAGE='mnlfa', a, b, theta, y, y_resp)
}

mnlfa_rcpp_calc_probs_gpcm_deriv <- function(a, b, theta, y, y_resp, Xdes_int, Xdes_slo, ind, is_b, uu) {
    .Call('_mnlfa_mnlfa_rcpp_calc_probs_gpcm_deriv', PACKAGE='mnlfa', a, b, theta, y, y_resp, Xdes_int, Xdes_slo, ind, is_b, uu)
}

mnlfa_rcpp_mstep_trait_unidim_fun <- function(theta, mu_p, sigma_p, post, weights) {
    .Call('_mnlfa_mnlfa_rcpp_mstep_trait_unidim_fun', PACKAGE='mnlfa', theta, mu_p, sigma_p, post, weights)
}

mnlfa_rcpp_mstep_trait_unidim_grad <- function(theta, mu_p, sigma_p, post, IM, IS, Xdes_mean, Xdes_sd, weights) {
    .Call('_mnlfa_mnlfa_rcpp_mstep_trait_unidim_grad', PACKAGE='mnlfa', theta, mu_p, sigma_p, post, IM, IS, Xdes_mean, Xdes_sd, weights)
}

